# Configuration of Hugo
# Guide: https://docs.hugoblox.com/tutorial/
# Hugo Documentation: https://gohugo.io/getting-started/configuration/#all-configuration-settings
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

title: "Creator's Blog (Hugo Theme)" # Website name
baseURL: 'https://example.com/' # Website URL

############################
## PAGE OPTIONS
############################

cascade:
  # Blog post options
  - _target:
      path: /blog/**
      kind: page
    pager: true
    editable: true
    hide_date: false
    show_date_updated: true
    reading_time: true
    commentable: true
    show_related: true
    share: true
    # Just use Breadcrumb for navigation on blog post pages?
    show_breadcrumb: false
    header:
      navbar:
        enable: true
  # Publication options
  - _target:
      path: /publication/**
      kind: page
    pager: false
    editable: false
    hide_date: true
    reading_time: false
    commentable: false
    show_related: false
    share: false
    show_authors: false
    show_date_updated: false
    show_breadcrumb: false
    header:
      navbar:
        enable: true
  # Preprint options (match publication look & feel)
  - _target:
      path: /preprint/**
      kind: page
    pager: false
    editable: false
    hide_date: true
    reading_time: false
    commentable: false
    show_related: false
    share: false
    show_authors: false
    show_date_updated: false
    show_breadcrumb: false
    header:
      navbar:
        enable: true

############################
## LANGUAGE
############################

defaultContentLanguage: en
hasCJKLanguage: false
defaultContentLanguageInSubdir: false
removePathAccents: true

############################
## ADVANCED
############################

build:
  writeStats: true
enableGitInfo: false
summaryLength: 30
pagination:
  pagerSize: 10
enableEmoji: true
enableRobotsTXT: true
footnotereturnlinkcontents: <sup>^</sup>
ignoreFiles: [\.ipynb$, .ipynb_checkpoints$, \.Rmd$, \.Rmarkdown$, _cache$]
disableAliases: true
outputs:
  home: [HTML, headers, redirects, backlinks]
  section: []
imaging:
  resampleFilter: lanczos
  quality: 90
  anchor: smart
  hint: picture
timeout: 600000
taxonomies: {}
disableKinds:
  - section
  - taxonomy
  - term
  - RSS
  - sitemap
  - robotsTXT
markup:
  _merge: deep
related:
  threshold: 80
  includeNewer: true
  toLower: true
  indices:
    - name: tags
      weight: 100
    - name: categories
      weight: 70
security:
  _merge: deep
sitemap:
  _merge: deep
minify:
  _merge: deep
