# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Preprints
    url: /#preprints
    weight: 15
  - name: Publications
    url: /#publications
    weight: 20
